### ISSUE TITLE
カード詳細のスタイル調整

### ISSUE THREAD

**Issue by h-kawamoto** [shin-dev/trello-design#4]
マークダウンで改行した時の表示が見辛い
margin-bottomが小さすぎるので調整できるようにプロパティを追加する

```css
.markeddown > *:not(:last-child) {
  margin-bottom: 1rem;
}
```
